In [ ]:
import numpy as np
import pandas as pd

## Importing the Dataset 

In [ ]:
dataset = pd.read_csv('../dataset/dataset_sampled.csv')

## Creating Bag of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)
X = cv.fit_transform(dataset['cleaned']).toarray()
y = dataset['Labels']

## Creating The Training set and the Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

## SVM

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

params = {'C':[1, 10], 'kernel':('poly','rbf','sigmoid')}

svc_classifier_grid = SVC()
svc_gridsearch = GridSearchCV(svc_classifier_grid, param_grid=params, scoring='accuracy', cv=10)
svc_gridsearch.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid={'C': [1, 10], 'kernel': ('poly', 'rbf', 'sigmoid')},
             scoring='accuracy')

In [ ]:
print("The best validation accuracy: ", svc_gridsearch.best_score_)
svc_gridsearch.best_estimator_.get_params()

The best validation accuracy:  0.5498888888888888


{'C': 1,
 'break_ties': False,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'scale',
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report
svc_classifier = svc_gridsearch.best_estimator_
y_pred_svm = svc_classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

[[ 30   2 218]
 [  7   5 217]
 [  9   0 512]]
              precision    recall  f1-score   support

           0       0.65      0.12      0.20       250
           1       0.71      0.02      0.04       229
           2       0.54      0.98      0.70       521

    accuracy                           0.55      1000
   macro avg       0.64      0.37      0.31      1000
weighted avg       0.61      0.55      0.42      1000

